### ISSUE TITLE
Add support for Linux 5.10

### ISSUE THREAD

**Issue by dromer** [dagargo/emu3fs#2]
Unable to build on Debian Stable with gcc `8.3.0`:
```
emu3fs/super.c:82:37: error: dereferencing pointer to incomplete type ‘struct block_device’
  u64 id = huge_encode_dev(sb->s_bdev->bd_dev);
```

My C-knowledge is too limited to know what's happening here ;)

**Comment by dagargo** [comment]
I have tested everything in my Debian stable system and it seems to compile and to work.

Since you're using a similar system, I suggest you to check your installed packages. More specifically, check the Linux headers package that match your kernel mayor and minor versions. In my case, `linux-headers-4.19.67`. 

The error you're having is related to not finding the `struct block_device`, which is defined [here](https://github.com/torvalds/linux/blob/4d856f72c10ecb060868ed10ff1b1453943fc6c8/include/linux/fs.h#L466).

I've just find out that struct is no longer defined in that file so this might be causing the error. Be sure you're compiling against the right kernel sources. To know which sources are being used look at the compilation output.

Here, I'm leaving you more information in case you need it.

This is my system.

```
$ uname -a
Linux leela 4.19.67 #1 SMP Mon Sep 30 18:17:33 CEST 2019 x86_64 GNU/Linux

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 

$ apt list --installed linux*
Listing... Done
linux-base/stable,now 4.6 all [installed,automatic]
linux-compiler-gcc-8-x86/stable,now 4.19.181-1 amd64 [installed,automatic]
linux-config-4.19/stable,now 4.19.181-1 amd64 [installed,automatic]
linux-headers-4.19.0-6-amd64/now 4.19.67-2+deb10u2 amd64 [installed,local]
linux-headers-4.19.0-6-common/now 4.19.67-2+deb10u2 all [installed,local]
linux-headers-4.19.67/now 4.19.67-1 amd64 [installed,local]
linux-image-4.19.0-14-amd64/stable,stable,now 4.19.171-2 amd64 [installed,automatic]
linux-image-4.19.0-16-amd64/stable,now 4.19.181-1 amd64 [installed,automatic]
linux-image-4.19.67-dbg/now 4.19.67-1 amd64 [installed,local]
linux-image-4.19.67/now 4.19.67-1 amd64 [installed,local]
linux-image-amd64/stable,now 4.19+105+deb10u11 amd64 [installed]
linux-kbuild-4.19/stable,now 4.19.181-1 amd64 [installed,automatic]
linux-libc-dev/stable,now 4.19.181-1 amd64 [installed,automatic]
linux-source-4.19/stable,now 4.19.181-1 all [installed]
```

This is the state of the repository. Regarding the vfs, no changes in the kernel interfaces have been done from tag 4.19 to tag 5.3, so you can compile the master branch safely.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git log     
commit a0a8d9916524a620181887f01cae704f8083c87b (HEAD -> master, tag: 5.3, origin/master, origin/HEAD)
Author: dagargo <dagargo@gmail.com>
Date:   Mon Sep 2 23:08:37 2019 +0200

    Improve marking volume as non empty
[...]
```

This is the compilation and installation.

```
$ make && sudo make install
make -C /lib/modules/4.19.67/build M=/home/david/Desarrollo/git/emu3fs modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.67'
  CC [M]  /home/david/Desarrollo/git/emu3fs/super.o
  CC [M]  /home/david/Desarrollo/git/emu3fs/inode.o
  CC [M]  /home/david/Desarrollo/git/emu3fs/file.o
  CC [M]  /home/david/Desarrollo/git/emu3fs/dir.o
  LD [M]  /home/david/Desarrollo/git/emu3fs/emu3_fs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/david/Desarrollo/git/emu3fs/emu3_fs.mod.o
  LD [M]  /home/david/Desarrollo/git/emu3fs/emu3_fs.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.19.67'
[sudo] password for david: 
make -C /lib/modules/4.19.67/build M=/home/david/Desarrollo/git/emu3fs modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.19.67'
  INSTALL /home/david/Desarrollo/git/emu3fs/emu3_fs.ko
  DEPMOD  4.19.67
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-4.19.67'
depmod -a
```

This is the testing.

```
$ cd tests
$ EMU3_MOUNTPOINT=/media/emu3 ./tests.sh
Inserting module...
Uncompressing image...
Mounting image...
Results: 1/1
Results: 2/2
Results: 3/3
Results: 4/4
Results: 5/5
Results: 6/6
Results: 7/7
Results: 8/8
Remounting...
Results: 9/9
Results: 10/10
Results: 11/11
Results: 12/12
Results: 13/13
Results: 14/14
Cleaning up...
```

**Comment by dromer** [comment]
Thnx for the detailed reply. I was sure that I had my kernel headers installed (I'm using a kernel from backports), but I will triple check this and try again :)

**Comment by dromer** [comment]
Hmm, most certainly have all kernel headers installed. However I have `5.10.0-0.bpo.5-amd64` (since you mentioned `no changes in the kernel interfaces have been done from tag 4.19 to tag 5.3`)

**Comment by dagargo** [comment]
What is the output of the `make`?

**Comment by dromer** [comment]
```
emu3fs$ make
make -C /lib/modules/5.10.0-0.bpo.5-amd64/build M=/home/dreamer/Sources/_audio/_samplers/emu3fs modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-0.bpo.5-amd64'
  CC [M]  /home/dreamer/Sources/_audio/_samplers/emu3fs/super.o
/home/dreamer/Sources/_audio/_samplers/emu3fs/super.c: In function ‘emu3_statfs’:
/home/dreamer/Sources/_audio/_samplers/emu3fs/super.c:82:37: error: dereferencing pointer to incomplete type ‘struct block_device’
  u64 id = huge_encode_dev(sb->s_bdev->bd_dev);
                                     ^~
make[3]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/scripts/Makefile.build:284: /home/dreamer/Sources/_audio/_samplers/emu3fs/super.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:1819: /home/dreamer/Sources/_audio/_samplers/emu3fs] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-0.bpo.5-amd64'
make: *** [Makefile:6: all] Error 
```

**Comment by dagargo** [comment]
I think I explained myself poorly before.

When I said _no changes in the kernel interfaces have been done from tag 4.19 to tag 5.3_ I was referring to the tags in emu3fs but also to the Linux kernel interfaces (defined in the kernel headers). So I can not guarantee that it will compile on kernels after 5.3.

Clearly, you are using headers for the 5.10 version so it could not compile. And that's what's happening. In fact, you can see that the struct is defined as an incomplete type [here](https://github.com/torvalds/linux/blob/2c85ebc57b3e1817b6ce1a6b703928e113a90442/include/linux/fs.h#L1451) and hence your error.

If you want to load the module into the 5.10 version, some changes need to be done in the code.
If not, change your headers to ones up to 5.3 version.

**Comment by dromer** [comment]
But why would I use 5.3 headers on a 5.10 kernel?

I guess I'll wait until compatibility is there.

**Comment by dagargo** [comment]
> But why would I use 5.3 headers on a 5.10 kernel?

Yeah, it makes no sense. Rereading your comments, I see my misunderstanding. Sorry for the confusion.

I'm gonna change the summary of the issue and keep this open.

I'll try to  take a look at this in the following weeks.

**Comment by dagargo** [comment]
I think I've fixed this. It was very simple. See 95b76a2ea8e38a68bbc224618000c7250a2d76e7 for details.

However, I have just tried this with kernel 5.11, which comes with yesterday's new Ubuntu release (21.04 hirsute hippo). So I can not confirm that it's working for you.

Let me know if this works with version 5.10.

May I ask what hardware sampler are you using with emu3fs?

**Comment by dromer** [comment]
`-rw-r--r-- 1 dreamer dreamer 1.6M Apr 23 18:56 emu3_fs.ko` << yay! \o/

I have an ESI-4000 that I think I've used emu3fs on before.
Also an Emulator IV, but not sure if that's a compatible fs.

**Comment by dagargo** [comment]
I was just asking because I read some weeks ago that the Emulators series IV (ESIs belong to series III) use the same filesystem and now I'm curious about this.

Perhaps, you could try it. If you can and it works, let me know.

I'm closing this.

**Comment by dromer** [comment]
In the past I've been using zip drives to transfer files. usb on the pc and scsi on the samplers.
Will have to dive into this stuff, but will see if I can do some nice tests.

**Comment by dagargo** [comment]
That would be great!

**Comment by raybellis** [comment]
> I was just asking because I read some weeks ago that the Emulators series IV (ESIs belong to series III) use the same filesystem and now I'm curious about this.

The E4 FS is fundamentally the same as the E3 FS, except that it has support for a single level of subdirectories.

Those subdirectory entries appear contiguously with the main directory table (i.e. before any data) but I didn't yet delve deeply into how they're indexed from the top directory, nor how the directory blocks grow if needed.

**Comment by dagargo** [comment]
Very nice to know. Thanks for the info.

Perhaps I could try to add support for this in the future. I've created #3 for this.

Do you have an ISO image of EIV disks containing directories?
